server:
  port: 9091

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/patientdb
    username: root
    password: Sa@14253669
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka
